export const ADMIN_ROUTE: string = '/admin'
export const LOGIN_ROUTE: string = '/login'
export const REGISTRATION_ROUTE: string = '/registration'
export const SHOP_ROUTE: string = '/'
export const CART_ROUTE: string = '/cart'
export const DEVICE_ROUTE: string = '/device'